### PR TITLE
PE-3988: Adds the pin icons

### PR DESCRIPTION
**Pull request by matibat**

### CODE REVIEW

**Comment by thiagocarvalhodev** [comment]
@matibat , after reviewing the new font, I saw that the icons are wrong (the size of them). We have some issues exporting the icon from Figma to Flutter, I apologize the documentation didn't mention it. Also, the icons are not from the Design System, but new icons are only for the ardrive app project.

#60 adds only the icon on the design system. If we want a custom behavior for that, we must add it on the app level by adding the icon directly there or by changing the icon I'm adding now.

image

**Comment by thiagocarvalhodev** [comment]
@matibat , that would be very helpful. If you still have the config.json, you can add to the PR.

**Comment by thiagocarvalhodev** [comment]
https://github.com/ardriveapp/ardrive-web/pull/1268#discussion_r1283174446, please update with the latest version from `main`

**Comment by matibat** [comment]
Uploaded the config JSON file and re-integrated `main` into here - @thiagocarvalhodev

**Review by thiagocarvalhodev — APPROVED** [review]
LGTM. After finishing the QA, we'll release these changes.

**Review by thiagocarvalhodev — APPROVED** [review]

**Pull request merged**
